// <auto-generated />
using Main.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace main.Migrations
{
    [DbContext(typeof(MeetingsContext))]
    [Migration("20190127132155_v3")]
    partial class v3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Main.Models.CheckUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Dob");

                    b.HasKey("Id");

                    b.ToTable("CheckUpdates");
                });

            modelBuilder.Entity("Main.Models.Meeting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EndDateTime");

                    b.Property<string>("IdLotus");

                    b.Property<int>("IdRoom");

                    b.Property<string>("Link");

                    b.Property<DateTime>("StartDateTime");

                    b.Property<string>("Who");

                    b.Property<bool>("check");

                    b.HasKey("Id");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("Main.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Deleted");

                    b.Property<string>("IdLotus");

                    b.Property<string>("Name");

                    b.Property<int>("attenders");

                    b.Property<bool>("computer");

                    b.Property<string>("email");

                    b.Property<bool>("microfonia");

                    b.Property<bool>("phone");

                    b.Property<string>("plano");

                    b.Property<int>("planta");

                    b.Property<bool>("projector");

                    b.Property<bool>("tv");

                    b.Property<bool>("videoconference");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
